-- Generated from data/diet and weight summarized.csv
begin;
alter table weights alter column value drop not null;
delete from weights;
insert into weights (entry_date, meal, value, unit, menu, symptoms, calories, fat, protein, source) values
  ('2025-08-27', 'other', 121.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-08', 'other', 120.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-10', 'other', 120.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-15', 'other', 118.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-16', 'other', 118.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-25', 'other', 117.8, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-28', 'other', 117.75, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-09-30', 'other', 114.5, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-10-03', 'other', 117.0, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-10-05', 'other', 114.5, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-10-14', 'other', 114.5, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-04', 'lunch', NULL, 'kg', 'Shaljam + 2 roti + bowl of yogurt', 'Water brash', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-04', 'dinner', NULL, 'kg', 'Channa Chawal 1 plate', 'Water brash', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-05', 'breakfast', NULL, 'kg', '1 bowl fruit chat', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-05', 'lunch', 111.8, 'kg', '450G daal Chawal', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-05', 'dinner', NULL, 'kg', '500G daal Chawal + 1 shami kebab + 1.5 quiche + 2 date mamol', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-06', 'breakfast', NULL, 'kg', 'Half plate fruit chat', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-06', 'lunch', 112.5, 'kg', '2 roti with shaljam', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-06', 'dinner', NULL, 'kg', '2 roti with 350g of aalu chicken', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-07', 'breakfast', NULL, 'kg', 'A bowl of saagu dana', 'less water brash', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-07', 'lunch', NULL, 'kg', '2 roti with 350g of aalu chicken', 'less water brash', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-07', 'dinner', NULL, 'kg', 'a plate of mix vegetable rice with 1 chicken malai boti piece', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-08', 'breakfast', NULL, 'kg', 'A bowl of poridge', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-08', 'lunch', NULL, 'kg', 'a plate of mix vegetable rice', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-08', 'dinner', NULL, 'kg', 'chicken fried rice with almond chicken', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-09', 'breakfast', 112.45, 'kg', '470g poridge', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-09', 'lunch', NULL, 'kg', '300g chicken shorba with 2 roti', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-09', 'dinner', NULL, 'kg', 'Mix vegetable rice 1 plate, 2 roti with 150g of chicken shorba', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-10', 'breakfast', NULL, 'kg', '470g porridge', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-10', 'lunch', NULL, 'kg', '2 roti with aalu ande', '2 loose motion', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-10', 'dinner', NULL, 'kg', '2 roti with chicken salan', '1 loose motion', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-11', 'breakfast', 111.2, 'kg', '400g porridge', '1 loose motion', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-11', 'lunch', NULL, 'kg', '2 roti with aalu ande', 'slightl discomfort in chest', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-11', 'dinner', 111.6, 'kg', '2 plate rice with yogurt with chicken piece', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-12', 'breakfast', 111.8, 'kg', 'Museli in milk', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-12', 'lunch', NULL, 'kg', '1 plate plain rice with chicken piece', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-12', 'dinner', NULL, 'kg', '2 plate daal chawal', 'slight discomfort in chest', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-13', 'breakfast', 111.9, 'kg', '1 bowl mueseli', '1 watery loose motion', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-13', 'lunch', NULL, 'kg', '1.5 plate white rice with aalo keema', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-13', 'dinner', NULL, 'kg', '1.5 plate white rice with aalo keema', 'slight pain in neck, slight burning in chest', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-14', 'breakfast', NULL, 'kg', '1 bowl mueseli', 'watery mouth', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-14', 'lunch', NULL, 'kg', 'shaljam with 2 roti', 'lots of stool, not watery, but not formed. some formed some mushy. pale yellow. last stool was yesterday after breakfast', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-14', 'dinner', NULL, 'kg', 'a bowl of shawarama and rice. 2 roti with shaljam', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-18', 'breakfast', 112.15, 'kg', 'Dalia', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-18', 'lunch', NULL, 'kg', 'white rice with chicken cubes', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-18', 'dinner', NULL, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-19', 'breakfast', 112.1, 'kg', 'Dalia', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-19', 'lunch', NULL, 'kg', 'Chicken Pulao', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-19', 'dinner', NULL, 'kg', NULL, NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-29', 'breakfast', 112.0, 'kg', 'oats', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-11-30', 'breakfast', 112.3, 'kg', 'oats', 'having difficulty in eating things like cucumber. food is getting struck near the epiglotis areas', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-12-20', 'breakfast', 110.9, 'kg', 'oats', 'no pain or discomfort, stool comes out like small bits and very pale in color', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-12-22', 'dinner', 111.55, 'kg', 'White Rice and yogurt', NULL, NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2025-12-25', 'breakfast', 110.15, 'kg', 'oats', 'no pain or discomfort, last stool came out quite normal', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2026-01-27', 'dinner', 109.85, 'kg', 'White rice with kofta and egg', 'Water brash', NULL, NULL, NULL, 'csv:diet and weight summarized.csv'),
  ('2026-01-31', 'lunch', 109.2, 'kg', 'White rice with egg and boiled vegetables', 'None. Feels alright. Minimal to no water brash since yesterday', NULL, NULL, NULL, 'csv:diet and weight summarized.csv');
commit;